"""added foliar

Revision ID: bb6f418831fd
Revises: aed6cd7294d3
Create Date: 2021-01-10 12:52:19.025228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6f418831fd'
down_revision = 'aed6cd7294d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foliarspray',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('date_of_apply', sa.Date(), nullable=True),
    sa.Column('content1', sa.Integer(), nullable=True),
    sa.Column('content2', sa.Integer(), nullable=True),
    sa.Column('content3', sa.Integer(), nullable=True),
    sa.Column('content4', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foliarspray')
    # ### end Alembic commands ###
